name: build rt-k3


on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ET0MACADDR: "00:11:22:33:44:11"    
  MACADDR1_24G: "00:11:22:33:44:22"
  MACADDR2_5G: "00:11:22:33:44:33"

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@v2
      # Runs a single command using the runners shell
         
    - name: Clone source code
      run: |       
        git clone https://github.com/godcong/test_k3_build
     
        cd test_k3_build
        echo "::set-env name=VERSION::$(git show-ref --heads -s)"
        echo "::set-env name=TAG::$(git show-ref --heads --hash=8)"
        
      
    - name: Test Replace
      run: |
        sudo ln -s $(pwd)/test_k3_build /opt/work
       
        cd  /opt/work
        echo "add version tag"
        sed -i 's/EXTENDNO=.*/&_${{ env.MERLIN_TAG }}/g' version.conf
       
        echo "replace mac address from $(cat rt-k3_nvram.txt | grep ^et0macaddr) to ${{ env.ET0MACADDR }}"
        sed -i 's/^\(et0macaddr=\).*/\1${{ env.ET0MACADDR }}/g' rt-k3_nvram.txt
        echo "replace mac 2.4g address from $(cat rt-k3_nvram.txt | grep ^1:macaddr) to ${{ env.MACADDR1_24G }}"
        sed -i 's/^\(1:macaddr=\).*/\1${{ env.MACADDR1_24G }}/g' rt-k3_nvram.txt
        echo "replace mac 5g address from $(cat rt-k3_nvram.txt | grep ^2:macaddr) to ${{ env.MACADDR2_5G }}"
        sed -i 's/^\(2:macaddr=\).*/\1${{ env.MACADDR2_5G }}/g' rt-k3_nvram.txt
        

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        artifacts: "/opt/work/rt-k3_nvram.txt,version.conf"
        allowUpdates: true 
        commit: master 
        tag: build_${{ env.TAG }}
        body: |
          this is only a latest build from master
          version: https://github.com/godcong/test_k3_build/commit/${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
